version: "3.7"



services:

  nginx:
    image: nginx
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data:/var/www/html
    ports: 
      - 8080:8080

  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfile
    volumes:
        - ./images:/app/wwwroot/images
    environment:
       ASPNETCORE_ENVIRONMENT: Development
       ASPNETCORE_URLS: http://+:80
       FrontClient1: http://localhost:4200
       FrontClient2: http://localhost:8080
       Issuer: https://s.x-01.ru
       Audience: https://x-01.ru
       ClientSecrets: client_secret_swagger
       Scopes: api1.read
       AdminPass: i-1967
       AdminEmail: admin@x-01.ru
       AdminPhone: +79002440328
       ConnectString: server=db;port=3306;UserId=root;Password=747Ii81FN3DL-test;
       From: admin@x-01.ru
       SmtpServer: smtp.mail.ru
       Port: 465
       Username: admin_mail@x-01.ru
       Password: t30gK5YGenyeGMVpuYip 
       Telegram_token_bot : "5200452570:AAG3HwpXmY0LHPzrbRvs4oHd_PQkXyiipsU"   
       Google_idToken: "344759916833-h3r1fju9hj53jd86d142tn44vta9vnsa.apps.googleusercontent.com"
       VK_Token : "VykbJYZq67IyNuwdZcEv"
    ports:
      - 80
    restart: always
    
  

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql:/usr/sbin/mysql
    environment:          
        MYSQL_ROOT_PASSWORD: 747Ii81FN3DL-test
        MYSQL_DATABASE: ShopDB
    ports:
      - 3306:3306
         
  
           
          

       
