version: "3.7"



services:

  nginx:
    image: nginx
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data:/var/www/html
    ports: 
      - 8080:8080

  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfile
    volumes:
        - ./images:/app/wwwroot/images
    environment:
       ASPNETCORE_ENVIRONMENT: Development
       ASPNETCORE_URLS: http://+:80
       FrontClient: http://localhost:4200
       Issuer: https://s.x-01.ru
       Audience: https://x-01.ru
       ClientSecrets: client_secret_swagger
       Scopes: api1.read
       AdminPass: i***
       AdminEmail: admin@****
       AdminPhone: +79002***
       ConnectString: server=db;port=3306;UserId=***;Password=****;
       From: admin@x-01.ru
       SmtpServer: smtp.mail.ru
       Port: 465
       Username: admin@***1.ru
       Password: ***      
    ports:
      - 80
    restart: always
    
  

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql:/usr/sbin/mysql
    environment:          
        MYSQL_ROOT_PASSWORD: *****
        MYSQL_DATABASE: ShopDB
    ports:
      - 3306:3306
         
  
           
          

       
