version: "3.7"



services:

  nginx:
    image: nginx
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data:/var/www/html
    ports: 
      - 8080:8080

  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockerfile
    volumes:
        - ./images:/app/wwwroot/images
    ports:
      - 80
    restart: always
    
  

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql:/usr/sbin/mysql
    environment:          
        MYSQL_ROOT_PASSWORD: 747Ii81FN3DL
        MYSQL_DATABASE: AuthUserDB
    ports:
      - 3306:3306
         
  
           
          

       